/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const check: (a: number, b: number) => [number, number];
export const check_modules: (a: number, b: number) => [number, number, number, number];
export const completion: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const definition: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const doc_manifest: (a: number, b: number) => [number, number, number, number];
export const doc_ssr_bundle: () => [number, number];
export const emit_scene: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const emit_scene_modules: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const emit_svg: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const folding_ranges: (a: number, b: number) => [number, number];
export const format: (a: number, b: number) => [number, number, number, number];
export const hover: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const layout_scene: (a: number, b: number) => [number, number, number, number];
export const outline: (a: number, b: number) => [number, number];
export const outline_modules: (a: number, b: number) => [number, number, number, number];
export const parse: (a: number, b: number) => [number, number];
export const references: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const rename_apply: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const render_doc_site: (a: number, b: number, c: number, d: number, e: any) => [number, number, number, number];
export const semantic_tokens: (a: number, b: number) => [number, number];
export const symbol_scene: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const symbol_svg: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const version: () => [number, number];
export const start: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
